version: '3.4'

services:
  db: 
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Numsay*1"
    ports:
      - 1433:1433
  gamesloan:
    image: ${DOCKER_REGISTRY-}gamesloan
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db

